# Позволяет настраивать конфигурацию линтера (англ. linter). 
# Библиотеки для линтера предоставляют стандартный набор правил, 
# который может быть применён в проекте, 
# но пользователь может изменять и дополнять этот набор в соответствии с требованиями проекта.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**]
  language:

linter:
  rules:
