# Определяем конфигурацию проекта и используется, 
# чтобы определить зависимости проекта, версии библиотек, настройки сборки 
# и другие свойства проекта.

name: notes_organizer
description: "Simple application for easy notes organization on Flutter (Dart)"
publish_to: 'none'
version: 1.0.0+1

homepage: https://github.com/UmbrellaLeaf5/notes_organizer
repository: https://github.com/UmbrellaLeaf5/notes_organizer
issue_tracker: https://github.com/UmbrellaLeaf5/notes_organizer/issues
# documentation:

# параметр, отвечающий за окружение проекта — версию Dart и Flutter.
environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# executables:
    ## При активации с помощью команды pub global activate и 
    ## ввода my_command_1 запустится bin/main.dart
    # my_command_1: main

flutter:
  uses-material-design: true

platforms:
  linux:
  web:
  windows:

# screenshots:
#   - description: 'Тут мы описываем, что показано на изображении.'  
#     path: path/to/image/**in**/package/500x500.webp **## А тут оставляем ссылку**
