name: Build Flutter Linux

on:
  workflow_dispatch:  # Позволяет запустить вручную
  push:
    branches:
      - main # Запускается при push в ветку main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # Выгружает код репозитория

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' 

      - run: flutter pub get

      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build clang libgtk-3-dev

      - run: flutter build linux --release

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: './build/linux/'